authors:
  pseudonymous_rex:
    name: John Doe
    description: Creator
    avatar: https://thumb.wikimedia.org/wikipedia/en/thumb/6/6e/University_of_Waterloo_seal.svg/960px-University_of_Waterloo_seal.svg.png?utm_source=en.wikipedia.org&utm_campaign=imageinfo&utm_content=thumbnail